refactor: remove fs-extra usage
electron/archaeologist pull request #49
Opened 2024-10-04 06:23 UTC by dsanders11

Not necessary so trim this dependency.

2024-10-04 07:19 UTC, MarshallOfSound approved these changes

2024-10-04 15:17 UTC, jkleinsc approved these changes

2024-10-04 15:20 UTC, jkleinsc requested changes
lint workflow needs to be update to node 20.

2024-10-04 16:52 UTC, dsanders11 commented
@jkleinsc, updated.

2024-10-10 08:28 UTC, codebytere approved these changes

2024-10-14 23:48 UTC, merged